Repository spring-projects/spring-session, pull requests merged in 2022-10, with the labels that each got.

#2176 Fix max inactive interval setters backwards compatibility
  spring-session-data-mongodb/src/main/java/org/springframework/session/data/mongo/MongoIndexedSessionRepository.java
  spring-session-data-mongodb/src/main/java/org/springframework/session/data/mongo/ReactiveMongoSessionRepository.java
  spring-session-data-redis/src/main/java/org/springframework/session/data/redis/ReactiveRedisSessionRepository.java
  spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java
  spring-session-hazelcast/src/main/java/org/springframework/session/hazelcast/HazelcastIndexedSessionRepository.java
  spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcIndexedSessionRepository.java
Labels: type: bug

#2181 Avoid inheritance in configuration classes
  spring-session-data-mongodb/src/main/java/org/springframework/session/data/mongo/config/annotation/web/http/MongoHttpSessionConfiguration.java
  spring-session-data-mongodb/src/main/java/org/springframework/session/data/mongo/config/annotation/web/reactive/ReactiveMongoWebSessionConfiguration.java
  spring-session-data-redis/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/AbstractRedisHttpSessionConfiguration.java
  spring-session-data-redis/src/main/java/org/springframework/session/data/redis/config/annotation/web/server/RedisWebSessionConfiguration.java
  spring-session-data-redis/src/test/java/org/springframework/session/data/redis/config/annotation/web/server/RedisWebSessionConfigurationTests.java
  spring-session-hazelcast/src/main/java/org/springframework/session/hazelcast/config/annotation/web/http/HazelcastHttpSessionConfiguration.java
  spring-session-hazelcast/src/test/java/org/springframework/session/hazelcast/config/annotation/web/http/HazelcastHttpSessionConfigurationTests.java
  spring-session-jdbc/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java
Labels: type: enhancement, in: core

#2139 Update Gradle Enterprise plugin to 3.11.1
  settings.gradle
Labels: in: build, type: dependency-upgrade

#2194 Optimize filter
  spring-session-core/src/main/java/org/springframework/session/web/http/SessionRepositoryFilter.java
  spring-session-core/src/test/java/org/springframework/session/web/http/SessionRepositoryFilterTests.java
Labels: type: enhancement, in: core

#2198 Update security config in samples
  spring-session-core/src/main/java/org/springframework/session/web/http/HeaderHttpSessionIdResolver.java
  spring-session-docs/modules/ROOT/examples/java/docs/security/RememberMeSecurityConfiguration.java
  spring-session-samples/spring-session-sample-boot-findbyusername/src/main/java/sample/config/SecurityConfig.java
  spring-session-samples/spring-session-sample-boot-hazelcast/src/main/java/sample/config/SecurityConfig.java
  spring-session-samples/spring-session-sample-boot-jdbc/src/main/java/sample/config/SecurityConfig.java
  spring-session-samples/spring-session-sample-boot-redis-json/src/main/java/sample/config/SecurityConfig.java
  spring-session-samples/spring-session-sample-boot-redis/src/main/java/sample/config/SecurityConfig.java
  spring-session-samples/spring-session-sample-boot-websocket/src/main/java/sample/config/WebSecurityConfig.java
  spring-session-samples/spring-session-sample-javaconfig-rest/src/main/java/sample/SecurityConfig.java
Labels: type: enhancement, in: docs

#2199 Add Spring Session BOM module
  settings.gradle
  spring-session-bom/spring-session-bom.gradle
  spring-session-docs/modules/ROOT/nav.adoc
  spring-session-docs/modules/ROOT/pages/modules.adoc
  spring-session-docs/modules/ROOT/pages/whats-new.adoc
Labels: type: enhancement, in: build
