Repository spring-projects/spring-session, pull requests merged in 2022-01, with the labels that each got.

#1969 Bump up Gradle enterprise plugin to 3.7.2
  settings.gradle
Labels: in: build, type: dependency-upgrade

#2012 Bump up Gradle plugin dependencies
  settings.gradle
Labels: type: task

#1988 Memory leak in Index for principal `null`
  spring-session-data-redis/src/integration-test/java/org/springframework/session/data/redis/RedisIndexedSessionRepositoryITests.java
  spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java
Labels: type: bug, status: duplicate, in: redis
