Repository spring-projects/spring-session, pull requests merged in 2022-11, with the labels that each got.

#2200 Avoid changing line endings of png and mmdb files
  .gitattributes
Labels: type: bug, in: build

#2208 label jpg as binary file in .gitattributes
  .gitattributes
Labels: status: waiting-for-triage

#2197 Update reference site link
  README.adoc
Labels: type: bug, in: docs
