Repository spring-projects/spring-session, pull requests merged in 2023-09, with the labels that each got.

#2384 Change charset in .editorconfig to utf-8
  .editorconfig
Labels: type: enhancement, in: build

#2457 Update to antora-ui-spring 0.3.6
  antora-playbook.yml
  lib/antora/templates/per-branch-antora-playbook.yml
  local-antora-playbook.yml
Labels: type: dependency-upgrade

#2460 Add missing ":" in RedisIndexedSessionRepository javadoc.
  spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java
Labels: type: bug, in: docs
