Repository spring-projects/spring-session, pull requests merged in 2025-04, with the labels that each got.

#3386 Update to Spring Security 6.5.0-rc1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#3264 Introduce CompositeHttpSessionIdResolver
  spring-session-core/src/main/java/org/springframework/session/web/http/CompositeHttpSessionIdResolver.java
  spring-session-core/src/test/java/org/springframework/session/web/http/CompositeHttpSessionIdResolverTests.java
Labels: type: enhancement

#3388 Update to spring-data-bom:2025.0.0-RC1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#3383 Polish usage of spring-boot-testcontainers
  spring-session-samples/spring-session-sample-boot-findbyusername/spring-session-sample-boot-findbyusername.gradle
  spring-session-samples/spring-session-sample-boot-findbyusername/src/integration-test/java/sample/FindByUsernameTests.java
  spring-session-samples/spring-session-sample-boot-jdbc-json-attribute/src/test/java/sample/JdbcJsonAttributeTests.java
  spring-session-samples/spring-session-sample-boot-jdbc-json-attribute/src/test/java/sample/TestContainersConfig.java
  spring-session-samples/spring-session-sample-boot-reactive-max-sessions/spring-session-sample-boot-reactive-max-sessions.gradle
  spring-session-samples/spring-session-sample-boot-reactive-max-sessions/src/test/java/com/example/TestcontainersConfig.java
  spring-session-samples/spring-session-sample-boot-reactive-redis-indexed/spring-session-sample-boot-reactive-redis-indexed.gradle
  spring-session-samples/spring-session-sample-boot-reactive-redis-indexed/src/test/java/com/example/TestcontainersConfig.java
  spring-session-samples/spring-session-sample-boot-redis-json/spring-session-sample-boot-redis-json.gradle
  spring-session-samples/spring-session-sample-boot-redis-json/src/integration-test/java/sample/HttpRedisJsonTest.java
  spring-session-samples/spring-session-sample-boot-redis-json/src/integration-test/java/sample/RedisSerializerTest.java
  spring-session-samples/spring-session-sample-boot-redis/spring-session-sample-boot-redis.gradle
  spring-session-samples/spring-session-sample-boot-redis/src/integration-test/java/sample/BootTests.java
  spring-session-samples/spring-session-sample-boot-webflux-custom-cookie/spring-session-sample-boot-webflux-custom-cookie.gradle
  spring-session-samples/spring-session-sample-boot-webflux-custom-cookie/src/integration-test/java/sample/AttributeTests.java
  spring-session-samples/spring-session-sample-boot-webflux/spring-session-sample-boot-webflux.gradle
  spring-session-samples/spring-session-sample-boot-webflux/src/integration-test/java/sample/AttributeTests.java
  spring-session-samples/spring-session-sample-boot-websocket/spring-session-sample-boot-websocket.gradle
  spring-session-samples/spring-session-sample-boot-websocket/src/integration-test/java/sample/ApplicationTests.java
Labels: in: docs
